# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 09:57
from __future__ import unicode_literals

import Customer.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('line_1', models.CharField(max_length=100)),
                ('line_2', models.CharField(max_length=100, null=True)),
                ('line_3', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('post_code', models.CharField(default='N/A', max_length=10)),
                ('misc_info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artefact', models.ImageField(upload_to=Customer.models.property_path)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(null=True, upload_to='avatars/')),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('address_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Address')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Party')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Customer.Event')),
                ('tax_paid', models.BooleanField()),
                ('eb_paid', models.BooleanField()),
                ('maintenance_paid', models.BooleanField()),
                ('well_maintained', models.BooleanField()),
                ('tenent_complaints', models.CharField(max_length=300)),
                ('external_feedback', models.CharField(max_length=300)),
                ('maint_required', models.CharField(max_length=300)),
                ('maint_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
            ],
            bases=('Customer.event',),
        ),
        migrations.AddField(
            model_name='event',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Property'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Event'),
        ),
    ]
