# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_auto_20170321_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars/'),
        ),
    ]
