# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_auto_20170506_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='picture',
            field=models.ImageField(null=True, upload_to='property/'),
        ),
    ]
