# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-20 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_party_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='status',
            field=models.CharField(default='Active', max_length=10),
        ),
    ]
