# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_auto_20170503_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=10),
        ),
    ]
